workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH  == $CI_DEFAULT_BRANCH'


secret_detection:
  stage: secret_detection
  tags:
    - shiftleft-azure-gitlab-runner
  before_script: []
  image:
    name: zricethezav/gitleaks:$GITLEAKS_IMAGE_VERSION
    entrypoint: [""]
  script: |
      echo "Installing gitleaks"
      gitleaks version
      echo "Running gitleaks Scan"
      gitleaks detect --source . --no-git --verbose
