name: Test Github actions

on:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  policy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Policy Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          skip_check: CKV2_GHA_1

  secret_detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Secret Detection
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: false
